CREATE DATABASE OFICINA;

CREATE TABLE FORNECEDOR(

IDFORNECEDOR INT PRIMARY KEY AUTO_INCREMENT,
RAZAOSOCIAL VARCHAR(50) UNIQUE NOT NULL,
CEP CHAR (8) NOT NULL,
EMAIL VARCHAR(50) UNIQUE NOT NULL,
TELEFONE CHAR (9) UNIQUE NOT NULL

);

CREATE TABLE FUNCIONARIO (
 
IDFUNCIONARIO INT PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR (50) NOT NULL,
CPF CHAR(11) UNIQUE NOT NULL,
EMAIL VARCHAR(50) UNIQUE NOT NULL,
TELEFONE CHAR(11) UNIQUE NOT NULL,
LOGIN VARCHAR(50) UNIQUE NOT NULL,
SENHA VARCHAR(50) UNIQUE NOT NULL

);

CREATE TABLE PRODUTO (

IDPRODUTO INT PRIMARY KEY AUTO_INCREMENT,
IDFORNECEDOR INT,
NOME_PRODUTO VARCHAR(50) NOT NULL,
PRECO DOUBLE NOT NULL,
QTD INT NOT NULL,

FOREIGN KEY(IDFORNECEDOR)
REFERENCES FORNECEDOR(IDFORNECEDOR)
);


CREATE TABLE ENTRADA (

IDENTRADA INT PRIMARY KEY AUTO_INCREMENT,
IDFORNECEDOR INT,
IDFUNCIONARIO INT,
DATAENTRADA DATE NOT NULL,
VALORTOTAL DOUBLE NOT NULL,

FOREIGN KEY(IDFORNECEDOR)
REFERENCES FORNECEDOR(IDFORNECEDOR),
FOREIGN KEY(IDFUNCIONARIO)
REFERENCES FUNCIONARIO(IDFUNCIONARIO)

);

CREATE TABLE SAIDA(

IDSAIDA INT PRIMARY KEY AUTO_INCREMENT,
IDFUNCIONARIO INT,
DATASAIDA DATE NOT NULL,
VALORTOTAL DOUBLE NOT NULL,

FOREIGN KEY(IDFUNCIONARIO)
REFERENCES FUNCIONARIO(IDFUNCIONARIO)
);

CREATE TABLE ITENSSAIDA(
IDITENSSAIDA INT PRIMARY KEY,
IDPRODUTO INT,
QTDVENDIDA INT NOT NULL,

FOREIGN KEY (IDPRODUTO)
REFERENCES PRODUTO(IDPRODUTO)
);